---
defaults:
  ttl: 60
  tags:
    - solanum

sources:
  - type: cpu
    per_core: true
  - type: cpu_freq
    class: Solanum::Source::CPUFreq
    period: 30
  - type: load
  - type: memory
  - type: diskstats
    devices:
      - sda
  - type: sensors
    sensors:
      coretemp: "Core 0"
      temp1: temp1
      temp2: temp2
      temp3: temp3

outputs:
  - type: print
  - type: riemann
    protocol: tls
    server: riemann.example.com
    port: 5554
