---
defaults:
  ttl: 60
  tags:
    - solanum

sources:
  - type: cpu
    detailed: false
    per_core: false
    usage_states:
      warning: 0.8
      critical: 0.9
  - type: uptime
    period: 60
  - type: load
    load_states:
      warning: 4
      critical: 8
  - type: memory
  - type: diskstats
    detailed: false
    devices:
      - sda
  - type: network
    detailed: false
    interfaces:
      - wlan0
  - type: certificate
    host: www.google.com
    period: 300
    attributes:
      ttl: 3600
    expiry_states:
      warning: 180
      critical: 30

outputs:
  - type: print
  - type: riemann
    host: riemann.example.com
    port: 5555
