---
defaults:
  ttl: 60
  tags:
    - solanum

sources:
  - type: cpu
    detailed: false
    per_core: false
    usage_states:
      warning: 0.8
      critical: 0.9
  - type: uptime
    period: 60
  - type: load
    load_states:
      warning: 4
      critical: 8
  - type: memory
  - type: disk-space
  - type: disk-stats
    detailed: false
    devices:
      - sda
  - type: network
    detailed: false
    interfaces:
      - wlan0
  - type: process
    pattern: postgresql
    user: postgresql
    min_states:
      critical: 0
  - type: tcp
    label: postgresql
    port: 5432
  - type: http
    period: 300
    label: vault
    url: 'http://localhost:8200/v1/sys/health'
    response_checks:
      - type: status
        values: [201, 429]
      - type: data
        key: initialized
        value: true
      - type: data
        key: sealed
        value: false
    record_fields:
      standby: standby
      version: version

outputs:
  - type: print
  - type: riemann
    host: riemann.example.com
    port: 5555
