version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      SOLANUM_LOG_APPENDER: nop
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "project.clj" }}
            - v1-
      - run: lein deps
      - run: lein check
      - run: lein test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "project.clj" }}
